export const LEVELS = [
    { name: "Proposition world",
      stages: [
          { name: "",
            rules: [],
            levels: [
                {
                    parameters: [ { name: "P", ty: "Type" } ],
                    variables: [ ],
                    hypotheses: [ { ty: "P" } ],
                    conclusion: { ty: "P" },
                    trivial: true,
                    autoComplete: true,
                    hint: "wiresHint",
                },
                {
                    parameters: [ { name: "P", ty: "Type" }, { name: "Q", ty: "Type" } ],
                    variables: [ ],
                    hypotheses: [ { ty: "P" }, { ty: "Q" } ],
                    conclusion: { ty: "Q" },
                    trivial: true,
                    autoComplete: true,
                    hint: "muxHint",
                },
            ],
          },
          { name: "∧",
            rules: [ "andI", "andE" ],
            levels: [
                {
                    parameters: [ { name: "P", ty: "Type" }, { name: "Q", ty: "Type" } ],
                    variables: [ ],
                    hypotheses: [ { ty: "P" }, { ty: "Q" } ],
                    conclusion: { ty: "P∧Q" },
                    trivial: true,
                    autoComplete: true,
                    hint: "introHint",
                },
                {
                    parameters: [ { name: "P", ty: "Type" } ],
                    variables: [ ],
                    hypotheses: [ { ty: "P" } ],
                    conclusion: { ty: "P∧P" },
                    trivial: true,
                    autoComplete: true,
                },
                {
                    parameters: [ { name: "P", ty: "Type" }, { name: "Q", ty: "Type" } ],
                    variables: [ ],
                    hypotheses: [ { ty: "P∧Q" } ],
                    conclusion: { ty: "P" },
                    trivial: true,
                    autoComplete: true,
                    hint: "elimHint",
                },
                {
                    parameters: [ { name: "P", ty: "Type" }, { name: "Q", ty: "Type" } ],
                    variables: [ ],
                    hypotheses: [ { ty: "P∧Q" } ],
                    conclusion: { ty: "Q" },
                    trivial: true,
                    autoComplete: true,
                },
                {
                    parameters: [ { name: "P", ty: "Type" }, { name: "Q", ty: "Type" } ],
                    variables: [ ],
                    hypotheses: [ { ty: "P∧Q" } ],
                    conclusion: { ty: "Q∧P" },
                    hint: "multiHint",
                },
                {
                    parameters: [ { name: "P", ty: "Type" }, { name: "Q", ty: "Type" }, { name: "R", ty: "Type" } ],
                    variables: [ ],
                    hypotheses: [ { ty: "(P∧Q)∧R" } ],
                    conclusion: { ty: "P∧R" },
                },
                {
                    parameters: [ { name: "P", ty: "Type" }, { name: "Q", ty: "Type" }, { name: "R", ty: "Type" } ],
                    variables: [ ],
                    hypotheses: [ { ty: "(P∧Q)∧R" } ],
                    conclusion: { ty: "P∧(Q∧R)" },
                },
                {
                    parameters: [ { name: "P", ty: "Type" }, { name: "Q", ty: "Type" }, { name: "R", ty: "Type" } ],
                    variables: [ ],
                    hypotheses: [ { ty: "P∧(Q∧R)" } ],
                    conclusion: { ty: "(P∧Q)∧R" },
                },
                {
                    parameters: [ { name: "P", ty: "Type" }, { name: "Q", ty: "Type" }, { name: "R", ty: "Type" }, { name: "S", ty: "Type" } ],
                    variables: [ ],
                    hypotheses: [ { ty: "(P∧Q)∧(R∧S)" } ],
                    conclusion: { ty: "R∧(S∧Q)" },
                },
            ]
          },
          { name: "⇒",
            rules: [ "impE", "impI" ],
            levels: [
                {
                    parameters: [ { name: "P", ty: "Type" }, { name: "Q", ty: "Type" } ],
                    variables: [ ],
                    hypotheses: [ { ty: "P⇒Q" }, { ty: "P" } ],
                    conclusion: { ty: "Q" },
                    trivial: true,
                    autoComplete: true,
                    hint: "impHint",
                },
                {
                    parameters: [ { name: "P", ty: "Type" } ],
                    variables: [ ],
                    hypotheses: [ ],
                    conclusion: { ty: "P⇒P" },
                    trivial: true,
                    hint: "bracketHint",
                },
                // {
                //                 parameters: [ { name: "P", ty: "Type" }, { name: "Q", ty: "Type" } ],
                //                 variables: [ ],
                //                 hypotheses: [ { ty: "Q" } ],
                //                 conclusion: { ty: "P⇒Q" },
                // },
                {
                    parameters: [ { name: "P", ty: "Type" }, { name: "Q", ty: "Type" } ],
                    variables: [ ],
                    hypotheses: [ ],
                    conclusion: { ty: "P⇒(Q⇒P)" },
                },
                {
                    parameters: [ { name: "P", ty: "Type" }, { name: "Q", ty: "Type" }, { name: "R", ty: "Type" } ],
                    variables: [ ],
                    hypotheses: [ { ty: "P⇒Q" }, { ty: "Q⇒R" } ],
                    conclusion: { ty: "P⇒R" },
                },
                {
                    parameters: [ { name: "P", ty: "Type" }, { name: "Q", ty: "Type" } ],
                    variables: [ ],
                    hypotheses: [ { ty: "P⇒(P⇒Q)" } ],
                    conclusion: { ty: "P⇒Q" },
                },
                {
                    parameters: [ { name: "P", ty: "Type" }, { name: "Q", ty: "Type" }, { name: "R", ty: "Type" }, { name: "S", ty: "Type" } ],
                    variables: [ ],
                    hypotheses: [ { ty: "P⇒Q" }, { ty: "P⇒R" }, { ty: "Q⇒S" }, { ty: "R⇒S" }, ],
                    conclusion: { ty: "P⇒S" },
                },
                {
                    parameters: [ { name: "P", ty: "Type" }, { name: "Q", ty: "Type" }, { name: "R", ty: "Type" } ],
                    variables: [ ],
                    hypotheses: [ { ty: "P⇒(Q⇒R)" }, ],
                    conclusion: { ty: "Q⇒(P⇒R)" },
                },
                {
                    parameters: [ { name: "P", ty: "Type" }, { name: "Q", ty: "Type" }, { name: "R", ty: "Type" } ],
                    variables: [ ],
                    hypotheses: [ { ty: "P⇒Q" }, ],
                    conclusion: { ty: "(Q⇒R)⇒(P⇒R)" },
                },
                {
                    parameters: [ { name: "P", ty: "Type" }, { name: "Q", ty: "Type" }, { name: "R", ty: "Type" } ],
                    variables: [ ],
                    hypotheses: [ { ty: "P⇒Q" }, ],
                    conclusion: { ty: "(R⇒P)⇒(R⇒Q)" },
                },
            ]
          },
          { name: "∧⇒",
            rules: [ "andE", "andI", "impE", "impI" ],
            levels: [
                {
                    parameters: [ { name: "P", ty: "Type" }, { name: "Q", ty: "Type" }, { name: "R", ty: "Type" } ],
                    variables: [ ],
                    hypotheses: [ { ty: "P⇒R" }, { ty: "Q⇒R" } ],
                    conclusion: { ty: "(P∧Q)⇒R" },
                    hint: "headHint",
                },
                {
                    parameters: [ { name: "P", ty: "Type" }, { name: "Q", ty: "Type" }, { name: "R", ty: "Type" } ],
                    variables: [ ],
                    hypotheses: [ { ty: "(P⇒Q)∧(P⇒R)" }, ],
                    conclusion: { ty: "P⇒(Q∧R)" },
                },
                {
                    parameters: [ { name: "P", ty: "Type" }, { name: "Q", ty: "Type" }, { name: "R", ty: "Type" } ],
                    variables: [ ],
                    hypotheses: [ { ty: "P⇒(Q∧R)" }, ],
                    conclusion: { ty: "(P⇒Q)∧(P⇒R)" },
                },
                {
                    parameters: [ { name: "P", ty: "Type" }, { name: "Q", ty: "Type" }, { name: "R", ty: "Type" } ],
                    variables: [ ],
                    hypotheses: [ { ty: "P⇒(Q⇒R)" }, ],
                    conclusion: { ty: "(P∧Q)⇒R" },
                },
                {
                    parameters: [ { name: "P", ty: "Type" }, { name: "Q", ty: "Type" }, { name: "R", ty: "Type" } ],
                    variables: [ ],
                    hypotheses: [ { ty: "(P∧Q)⇒R" }, ],
                    conclusion: { ty: "P⇒(Q⇒R)" },
                },
                {
                    parameters: [ { name: "P", ty: "Type" }, { name: "Q", ty: "Type" }, { name: "R", ty: "Type" }, { name: "S", ty: "Type" } ],
                    variables: [ ],
                    hypotheses: [ { ty: "P⇒Q" }, { ty: "R⇒S" }, ],
                    conclusion: { ty: "(P∧R)⇒(Q∧S)" },
                },
            ]
          },
          { name: "∨",
            rules: [ "orE", "orI1", "orI2" ],
            levels: [
                {
                    parameters: [ { name: "P", ty: "Type" }, { name: "Q", ty: "Type" } ],
                    variables: [ ],
                    hypotheses: [ { ty: "P" } ],
                    conclusion: { ty: "P∨Q" },
                    trivial: true,
                    autoComplete: true,
                    hint: "orHint",
                },
                {
                    parameters: [ { name: "P", ty: "Type" }, { name: "Q", ty: "Type" } ],
                    variables: [ ],
                    hypotheses: [ { ty: "Q" } ],
                    conclusion: { ty: "P∨Q" },
                    trivial: true,
                    autoComplete: true,
                },
                {
                    parameters: [ { name: "P", ty: "Type" } ],
                    variables: [ ],
                    hypotheses: [ { ty: "P" } ],
                    conclusion: { ty: "P∨P" },
                    trivial: true,
                    autoComplete: true,
                },
                {
                    parameters: [ { name: "P", ty: "Type" } ],
                    variables: [ ],
                    hypotheses: [ { ty: "P∨P" } ],
                    conclusion: { ty: "P" },
                    hint: "casesHint",
                },
                {
                    parameters: [ { name: "P", ty: "Type" }, { name: "Q", ty: "Type" } ],
                    variables: [ ],
                    hypotheses: [ { ty: "P∨Q" } ],
                    conclusion: { ty: "Q∨P" },
                },
                {
                    parameters: [ { name: "P", ty: "Type" }, { name: "Q", ty: "Type" }, { name: "R", ty: "Type" } ],
                    variables: [ ],
                    hypotheses: [ { ty: "(P∨Q)∨R" } ],
                    conclusion: { ty: "P∨(Q∨R)" },
                    hint: "casesGoalHint",
                },
                {
                    parameters: [ { name: "P", ty: "Type" }, { name: "Q", ty: "Type" }, { name: "R", ty: "Type" } ],
                    variables: [ ],
                    hypotheses: [ { ty: "P∨(Q∨R)" } ],
                    conclusion: { ty: "(P∨Q)∨R" },
                },
                {
                    parameters: [ { name: "P", ty: "Type" }, { name: "Q", ty: "Type" }, { name: "R", ty: "Type" }, { name: "S", ty: "Type" } ],
                    variables: [ ],
                    hypotheses: [ { ty: "R∨(S∨Q)" } ],
                    conclusion: { ty: "(P∨Q)∨(R∨S)" },
                },
                {
                    parameters: [ { name: "P", ty: "Type" }, { name: "Q", ty: "Type" } ],
                    variables: [ ],
                    hypotheses: [ { ty: "P∨P" } ],
                    conclusion: { ty: "P∨Q" },
                },
            ]
          },
          { name: "∧∨",
            rules: [ "andE", "andI", "orE", "orI1", "orI2" ],
            levels: [
                {
                    parameters: [ { name: "P", ty: "Type" }, { name: "Q", ty: "Type" } ],
                    variables: [ ],
                    hypotheses: [ { ty: "P∧Q" } ],
                    conclusion: { ty: "P∨Q" },
                },
                {
                    parameters: [ { name: "P", ty: "Type" }, { name: "Q", ty: "Type" } ],
                    variables: [ ],
                    hypotheses: [ { ty: "P∨(Q∧P)" } ],
                    conclusion: { ty: "P" },
                },
                {
                    parameters: [ { name: "P", ty: "Type" }, { name: "Q", ty: "Type" }, { name: "R", ty: "Type" } ],
                    variables: [ ],
                    hypotheses: [ { ty: "P∧(Q∨R)" } ],
                    conclusion: { ty: "(P∧Q)∨R" },
                },
                {
                    parameters: [ { name: "P", ty: "Type" }, { name: "Q", ty: "Type" }, { name: "R", ty: "Type" } ],
                    variables: [ ],
                    hypotheses: [ { ty: "P∧(Q∨R)" } ],
                    conclusion: { ty: "(P∧Q)∨(P∧R)" },
                },
                {
                    parameters: [ { name: "P", ty: "Type" }, { name: "Q", ty: "Type" }, { name: "R", ty: "Type" } ],
                    variables: [ ],
                    hypotheses: [ { ty: "(P∧Q)∨(P∧R)" } ],
                    conclusion: { ty: "P∧(Q∨R)" },
                },
                {
                    parameters: [ { name: "P", ty: "Type" }, { name: "Q", ty: "Type" }, { name: "R", ty: "Type" } ],
                    variables: [ ],
                    hypotheses: [ { ty: "P∨(Q∧R)" } ],
                    conclusion: { ty: "(P∨Q)∧(P∨R)" },
                },
                {
                    parameters: [ { name: "P", ty: "Type" }, { name: "Q", ty: "Type" }, { name: "R", ty: "Type" } ],
                    variables: [ ],
                    hypotheses: [ { ty: "(P∨Q)∧(P∨R)" } ],
                    conclusion: { ty: "P∨(Q∧R)" },
                },
            ]
          },
          { name: "∧∨⇒",
            rules: [ "andE", "andI", "impE", "impI", "orE", "orI1", "orI2" ],
            levels: [
                {
                    parameters: [ { name: "P", ty: "Type" }, { name: "Q", ty: "Type" }, { name: "R", ty: "Type" } ],
                    variables: [ ],
                    hypotheses: [ { ty: "P⇒R" }, { ty: "Q⇒R" } ],
                    conclusion: { ty: "(P∨Q)⇒R" },
                },
                {
                    parameters: [ { name: "P", ty: "Type" }, { name: "Q", ty: "Type" }, { name: "R", ty: "Type" } ],
                    variables: [ ],
                    hypotheses: [ { ty: "(P⇒R)∧(Q⇒R)" } ],
                    conclusion: { ty: "(P∨Q)⇒R" },
                },
                {
                    parameters: [ { name: "P", ty: "Type" }, { name: "Q", ty: "Type" }, { name: "R", ty: "Type" } ],
                    variables: [ ],
                    hypotheses: [ { ty: "(P∨Q)⇒R" } ],
                    conclusion: { ty: "(P⇒R)∧(Q⇒R)" },
                },
                {
                    parameters: [ { name: "P", ty: "Type" }, { name: "Q", ty: "Type" }, { name: "R", ty: "Type" } ],
                    variables: [ ],
                    hypotheses: [ { ty: "(P⇒R)∨(Q⇒R)" } ],
                    conclusion: { ty: "(P∧Q)⇒R" },
                },
                {
                    parameters: [ { name: "P", ty: "Type" }, { name: "Q", ty: "Type" }, { name: "R", ty: "Type" } ],
                    variables: [ ],
                    hypotheses: [ { ty: "(P⇒Q)∨(P⇒R)" } ],
                    conclusion: { ty: "P⇒(Q∨R)" },
                },
                {
                    parameters: [ { name: "P", ty: "Type" }, { name: "Q", ty: "Type" }, { name: "R", ty: "Type" }, { name: "S", ty: "Type" } ],
                    variables: [ ],
                    hypotheses: [ { ty: "P⇒Q" }, { ty: "R⇒S" } ],
                    conclusion: { ty: "(P∨R)⇒(Q∨S)" },
                },
            ]
          },
      ]
    },
    { name: "Advanced proposition world",
      stages: [
          { name: "X",
            rules: [],
            levels: [],
          },
          { name: "⇔∧",
            rules: [ "andE", "andI", "iffI", "iffE1", "iffE2" ],
            levels: [
                {
                    parameters: [ { name: "P", ty: "Type" } ],
                    variables: [ ],
                    hypotheses: [ ],
                    conclusion: { ty: "P⇔P" },
                    hint: "iffHint",
                },
                {
                    parameters: [ { name: "P", ty: "Type" } ],
                    variables: [ ],
                    hypotheses: [ ],
                    conclusion: { ty: "P⇔(P∧P)" },
                },
                {
                    parameters: [ { name: "P", ty: "Type" }, { name: "Q", ty: "Type" } ],
                    variables: [ ],
                    hypotheses: [ { ty: "P⇔Q" } ],
                    conclusion: { ty: "Q⇔P" },
                },
                {
                    parameters: [ { name: "P", ty: "Type" }, { name: "Q", ty: "Type" }, { name: "R", ty: "Type" } ],
                    variables: [ ],
                    hypotheses: [ { ty: "P⇔Q" }, { ty: "Q⇔R" } ],
                    conclusion: { ty: "P⇔R" },
                },
                {
                    parameters: [ { name: "P", ty: "Type" }, { name: "Q", ty: "Type" } ],
                    variables: [ ],
                    hypotheses: [ ],
                    conclusion: { ty: "(P∧Q)⇔(Q∧P)" },
                },
                {
                    parameters: [ { name: "P", ty: "Type" }, { name: "Q", ty: "Type" }, { name: "R", ty: "Type" } ],
                    variables: [ ],
                    hypotheses: [ { ty: "P⇔Q" } ],
                    conclusion: { ty: "(P∧R)⇔(Q∧R)" },
                },
            ]
          },
          { name: "⇔∨⇒",
            rules: [ "impE", "impI", "orE", "orI1", "orI2", "iffI", "iffE1", "iffE2" ],
            levels: [
                {
                    parameters: [ { name: "P", ty: "Type" } ],
                    variables: [ ],
                    hypotheses: [ ],
                    conclusion: { ty: "P⇔(P∨P)" },
                },
                {
                    parameters: [ { name: "P", ty: "Type" }, { name: "Q", ty: "Type" } ],
                    variables: [ ],
                    hypotheses: [ ],
                    conclusion: { ty: "(P∨Q)⇔(Q∨P)" },
                },
                {
                    parameters: [ { name: "P", ty: "Type" }, { name: "Q", ty: "Type" }, { name: "R", ty: "Type" } ],
                    variables: [ ],
                    hypotheses: [ { ty: "P⇔Q" } ],
                    conclusion: { ty: "(P∨R)⇔(Q∨R)" },
                },
                {
                    parameters: [ { name: "P", ty: "Type" }, { name: "Q", ty: "Type" }, { name: "R", ty: "Type" } ],
                    variables: [ ],
                    hypotheses: [ { ty: "P⇔Q" } ],
                    conclusion: { ty: "(P⇒R)⇔(Q⇒R)" },
                },
                {
                    parameters: [ { name: "P", ty: "Type" }, { name: "Q", ty: "Type" }, { name: "R", ty: "Type" } ],
                    variables: [ ],
                    hypotheses: [ { ty: "P⇔Q" } ],
                    conclusion: { ty: "(R⇒P)⇔(R⇒Q)" },
                },
            ]
          },
          { name: "⊤⇔∧∨⇒",
            rules: [ "topI", "andI", "andE", "orI1", "orI2", "orE", "impI", "impE", "iffI", "iffE1", "iffE2" ],
            levels: [
                {
                    parameters: [ ],
                    variables: [ ],
                    hypotheses: [ ],
                    conclusion: { ty: "⊤" },
                    trivial: true,
                    hint: "topHint",
                },
                {
                    parameters: [ { name: "P", ty: "Type" } ],
                    variables: [ ],
                    hypotheses: [ ],
                    conclusion: { ty: "(P⇒P)⇔⊤" },
                },
                {
                    parameters: [ { name: "P", ty: "Type" } ],
                    variables: [ ],
                    hypotheses: [ ],
                    conclusion: { ty: "(⊤∧P)⇔P" },
                },
                {
                    parameters: [ { name: "P", ty: "Type" } ],
                    variables: [ ],
                    hypotheses: [ ],
                    conclusion: { ty: "(⊤∨P)⇔⊤" },
                },
                {
                    parameters: [ { name: "P", ty: "Type" } ],
                    variables: [ ],
                    hypotheses: [ ],
                    conclusion: { ty: "(⊤⇒P)⇔P" },
                },
                {
                    parameters: [ { name: "P", ty: "Type" } ],
                    variables: [ ],
                    hypotheses: [ ],
                    conclusion: { ty: "(P⇒⊤)⇔⊤" },
                },
                {
                    parameters: [ { name: "P", ty: "Type" } ],
                    variables: [ ],
                    hypotheses: [ ],
                    conclusion: { ty: "(⊤⇔P)⇔P" },
                },
            ]
          },
          { name: "⊥⊤⇔∧∨⇒",
            rules: [ "andI", "andE", "orI1", "orI2", "orE", "impI", "impE", "botE", "iffI", "iffE1", "iffE2", "topI" ],
            levels: [
                {
                    parameters: [ { name: "P", ty: "Type" } ],
                    variables: [ ],
                    hypotheses: [ { ty: "⊥" } ],
                    conclusion: { ty: "P" },
                    trivial: true,
                    hint: "botHint",
                },
                {
                    parameters: [ { name: "P", ty: "Type" } ],
                    variables: [ ],
                    hypotheses: [ ],
                    conclusion: { ty: "(⊥∧P)⇔⊥" },
                },
                {
                    parameters: [ { name: "P", ty: "Type" } ],
                    variables: [ ],
                    hypotheses: [ ],
                    conclusion: { ty: "(⊥∨P)⇔P" },
                },
                {
                    parameters: [ { name: "P", ty: "Type" } ],
                    variables: [ ],
                    hypotheses: [ ],
                    conclusion: { ty: "(⊥⇒P)⇔⊤" },
                },
            ],
          },
          { name: "∧∨⇒",
            rules: [ "andE", "andI", "impE", "impI", "orE", "orI1", "orI2" ],
            levels: [
                {
                    parameters: [ { name: "P", ty: "Type" }, { name: "Q", ty: "Type" }, { name: "R", ty: "Type" } ],
                    variables: [ ],
                    hypotheses: [ { ty: "P⇒Q" }, { ty: "P⇒(Q⇒R)" }, ],
                    conclusion: { ty: "P⇒R" },
                },
                {
                    parameters: [ { name: "P", ty: "Type" }, { name: "Q", ty: "Type" } ],
                    variables: [ ],
                    hypotheses: [ { ty: "P⇒(P⇒Q)" }, { ty: "(P⇒Q)⇒P" } ],
                    conclusion: { ty: "Q" },
                    hint: "multiUseHint",
                },
                {
                    parameters: [ { name: "P", ty: "Type" }, { name: "Q", ty: "Type" }, { name: "R", ty: "Type" }, ],
                    variables: [ ],
                    hypotheses: [ { ty: "(P⇒Q)⇒R" }, { ty: "(Q⇒R)⇒P" }, { ty: "(R⇒P)⇒Q" } ],
                    conclusion: { ty: "P∧(Q∧R)" },
                    blocks: 10,
                },
                {
                    parameters: [ { name: "P", ty: "Type" }, { name: "Q", ty: "Type" }, { name: "R", ty: "Type" }, { name: "S", ty: "Type" } ],
                    variables: [ ],
                    hypotheses: [ { ty: "P⇒(Q∧R)" }, { ty: "(P∧Q)⇒S" }, { ty: "(P⇒S)⇒(Q⇒P)" }  ],
                    conclusion: { ty: "Q⇒(R∧S)" },
                },
                {
                    parameters: [ { name: "P", ty: "Type" }, { name: "Q", ty: "Type" } ],
                    variables: [ ],
                    hypotheses: [ ],
                    conclusion: { ty: "((P∨(P⇒Q))⇒Q)⇒Q" },
                },
            ]
          }
      ]
    },
    { name: "Quantifier world",
      stages: [
          { name: "∀⇒⊤",
            rules: [ "impI", "impE", "allE", "allI", "topI" ],
            levels: [
                {
                    parameters: [ { name: "A", ty: "Type" }, { name: "P", ty: "A→Type" } ],
                    variables: [ { name: "a", ty: "A" } ],
                    hypotheses: [ { ty: "∀x∈A,P(x)" } ],
                    conclusion: { ty: "P(a)" },
                    trivial: true,
                    hint: "valueHint",
                },
                {
                    parameters: [ { name: "A", ty: "Type" }, { name: "P", ty: "Type" } ],
                    variables: [ ],
                    hypotheses: [ { ty: "P" } ],
                    conclusion: { ty: "∀x∈A,P" },
                    trivial: true,
                    hint: "variableHint",
                },
                {
                    parameters: [ { name: "A", ty: "Type" }, { name: "P", ty: "Type" }, { name: "Q", ty: "A→Type" } ],
                    variables: [ ],
                    hypotheses: [ { ty: "∀x∈A,(P⇒Q(x))" } ],
                    conclusion: { ty: "P⇒(∀x∈A,Q(x))" },
                },
                {
                    parameters: [ { name: "A", ty: "Type" }, { name: "P", ty: "Type" }, { name: "Q", ty: "A→Type" } ],
                    variables: [ ],
                    hypotheses: [{ ty: "P⇒(∀x∈A,Q(x))" } ],
                    conclusion: { ty: "∀x∈A,(P⇒Q(x))" },
                },
                {
                    parameters: [ { name: "A", ty: "Type" }, { name: "B", ty: "Type" }, { name: "P", ty: "A×B→Type" } ],
                    variables: [ ],
                    hypotheses: [ { ty: "∀x∈A,∀y∈B,P(x,y)" } ],
                    conclusion: { ty: "∀y∈B,∀x∈A,P(x,y)" },
                },
                {
                    parameters: [ { name: "A", ty: "Type" } ],
                    variables: [ ],
                    hypotheses: [ ],
                    conclusion: { ty: "∀x∈A,⊤" },
                },
                {
                    parameters: [ { name: "A", ty: "Type" }, { name: "P", ty: "A×A→Type" } ],
                    variables: [ ],
                    hypotheses: [ { ty: "∀x∈A,∀y∈A,P(x,y)" } ],
                    conclusion: { ty: "∀x∈A,P(x,x)" },
                },
                {
                    parameters: [ { name: "A", ty: "Type" }, { name: "P", ty: "A→Type" }, { name: "Q", ty: "A→Type" }  ],
                    variables: [ ],
                    hypotheses: [ { ty: "∀x∈A,(P(x)⇒Q(x))" } ],
                    conclusion: { ty: "(∀x∈A,P(x))⇒(∀x∈A,Q(x))" },
                },
            ]
          },
          { name: "∀∧∨",
            rules: [ "andI", "andE", "orI1", "orI2", "orE", "allE", "allI" ],
            levels: [
                {
                    parameters: [ { name: "A", ty: "Type" }, { name: "P", ty: "A→Type" } ],
                    variables: [ { name: "a", ty: "A" }, { name: "b", ty: "A" } ],
                    hypotheses: [ { ty: "∀x∈A,P(x)" } ],
                    conclusion: { ty: "P(a)∧P(b)" },
                },
                {
                    parameters: [ { name: "A", ty: "Type" }, { name: "P", ty: "Type" }, { name: "Q", ty: "A→Type" } ],
                    variables: [ ],
                    hypotheses: [ { ty: "P∧(∀x∈A,Q(x))" } ],
                    conclusion: { ty: "∀x∈A,(P∧Q(x))" },
                },
                {
                    parameters: [ { name: "A", ty: "Type" }, { name: "P", ty: "Type" }, { name: "Q", ty: "A→Type" } ],
                    variables: [ ],
                    hypotheses: [ { ty: "P∨(∀x∈A,Q(x))" } ],
                    conclusion: { ty: "∀x∈A,(P∨Q(x))" },
                },
                {
                    parameters: [ { name: "A", ty: "Type" }, { name: "P", ty: "A→Type" }, { name: "Q", ty: "A→Type" }  ],
                    variables: [ ],
                    hypotheses: [ { ty: "∀x∈A,(P(x)∧Q(x))" } ],
                    conclusion: { ty: "(∀x∈A,P(x))∧(∀x∈A,Q(x))" },
                },
                {
                    parameters: [ { name: "A", ty: "Type" }, { name: "P", ty: "A→Type" }, { name: "Q", ty: "A→Type" }  ],
                    variables: [ ],
                    hypotheses: [ { ty: "(∀x∈A,P(x))∧(∀x∈A,Q(x))" } ],
                    conclusion: { ty: "∀x∈A,(P(x)∧Q(x))" },
                },
                {
                    parameters: [ { name: "A", ty: "Type" }, { name: "P", ty: "A→Type" }, { name: "Q", ty: "A→Type" }  ],
                    variables: [ ],
                    hypotheses: [ { ty: "(∀x∈A,P(x))∨(∀x∈A,Q(x))" } ],
                    conclusion: { ty: "∀x∈A,(P(x)∨Q(x))" },
                },
                {
                    parameters: [ { name: "A", ty: "Type" }, { name: "P", ty: "Type" }, { name: "Q", ty: "A→Type" } ],
                    variables: [ { name: "a", ty: "A" } ],
                    hypotheses: [ { ty: "∀x∈A,(P∧Q(x))" } ],
                    conclusion: { ty: "P∧(∀x∈A,Q(x))" },
                },
            ]
          },
          { name: "∃⇒⊤⊥",
            rules: [ "impI", "impE", "exE", "exI", "topI", "botE" ],
            levels: [
                {
                    parameters: [ { name: "A", ty: "Type" }, { name: "P", ty: "A→Type" } ],
                    variables: [ { name: "a", ty: "A" } ],
                    hypotheses: [ { ty: "P(a)" } ],
                    conclusion: { ty: "∃x∈A,P(x)" },
                    trivial: true,
                    hint: "exHint",
                },
                {
                    parameters: [ { name: "A", ty: "Type" }, { name: "P", ty: "Type" } ],
                    variables: [ { name: "a", ty: "A" } ],
                    hypotheses: [ { ty: "P" } ],
                    conclusion: { ty: "∃x∈A,P" },
                    trivial: true,
                },
                {
                    parameters: [ { name: "A", ty: "Type" }, { name: "P", ty: "Type" } ],
                    variables: [ ],
                    hypotheses: [ { ty: "∃x∈A,P" } ],
                    conclusion: { ty: "P" },
                    trivial: true,
                },
                {
                    parameters: [ { name: "A", ty: "Type" }, { name: "B", ty: "Type" }, { name: "P", ty: "A×B→Type" } ],
                    variables: [ ],
                    hypotheses: [ { ty: "∃x∈A,∃y∈B,P(x,y)" } ],
                    conclusion: { ty: "∃y∈B,∃x∈A,P(x,y)" },
                },
                {
                    parameters: [ { name: "A", ty: "Type" }, { name: "P", ty: "Type" }, { name: "Q", ty: "A→Type" } ],
                    variables: [ ],
                    hypotheses: [ { ty: "∃x∈A,(P⇒Q(x))" }, { ty: "P" } ],
                    conclusion: { ty: "∃x∈A,Q(x)" },
                },
                {
                    parameters: [ { name: "A", ty: "Type" }, { name: "P", ty: "A→Type" }, { name: "Q", ty: "Type" } ],
                    variables: [ { name: "a", ty: "A" } ],
                    hypotheses: [ { ty: "(∃x∈A,P(x))⇒Q" } ],
                    conclusion: { ty: "P(a)⇒Q" },
                },
                {
                    parameters: [ { name: "A", ty: "Type" }, { name: "P", ty: "A→Type" } ],
                    variables: [ ],
                    hypotheses: [ { ty: "∃x∈A,P(x)" } ],
                    conclusion: { ty: "∃x∈A,⊤" },
                },
                {
                    parameters: [ { name: "A", ty: "Type" }, { name: "P", ty: "Type" } ],
                    variables: [ ],
                    hypotheses: [ { ty: "∃x∈A,⊥" } ],
                    conclusion: { ty: "P" },
                },
                {
                    parameters: [ { name: "A", ty: "Type" }, { name: "P", ty: "A×A→Type" } ],
                    variables: [ ],
                    hypotheses: [ { ty: "∃x∈A,P(x,x)" } ],
                    conclusion: { ty: "∃x∈A,∃y∈A,P(x,y)" },
                },
            ]
          },
          { name: "∃∧∨",
            rules: [ "andI", "andE", "orE", "orI1", "orI2", "exE", "exI" ],
            levels: [
                {
                    parameters: [ { name: "A", ty: "Type" }, { name: "P", ty: "Type" }, { name: "Q", ty: "A→Type" }  ],
                    variables: [ ],
                    hypotheses: [ { ty: "∃x∈A,(P∧Q(x))" } ],
                    conclusion: { ty: "P∧(∃x∈A,Q(x))" },
                },
                {
                    parameters: [ { name: "A", ty: "Type" }, { name: "P", ty: "Type" }, { name: "Q", ty: "A→Type" }  ],
                    variables: [ ],
                    hypotheses: [ { ty: "P∧(∃x∈A,Q(x))" } ],
                    conclusion: { ty: "∃x∈A,(P∧Q(x))" },
                },
                {
                    parameters: [ { name: "A", ty: "Type" }, { name: "P", ty: "A→Type" }, { name: "Q", ty: "A→Type" }  ],
                    variables: [ ],
                    hypotheses: [ { ty: "∃x∈A,(P(x)∧Q(x))" } ],
                    conclusion: { ty: "(∃x∈A,P(x))∧(∃x∈A,Q(x))" },
                },
                {
                    parameters: [ { name: "A", ty: "Type" }, { name: "P", ty: "Type" }, { name: "Q", ty: "A→Type" }  ],
                    variables: [ ],
                    hypotheses: [ { ty: "∃x∈A,(P∨Q(x))" } ],
                    conclusion: { ty: "P∨(∃x∈A,Q(x))" },
                },
                {
                    parameters: [ { name: "A", ty: "Type" }, { name: "P", ty: "A→Type" }, { name: "Q", ty: "A→Type" }  ],
                    variables: [ ],
                    hypotheses: [ { ty: "∃x∈A,(P(x)∨Q(x))" } ],
                    conclusion: { ty: "(∃x∈A,P(x))∨(∃x∈A,Q(x))" },
                },
                {
                    parameters: [ { name: "A", ty: "Type" }, { name: "P", ty: "A→Type" }, { name: "Q", ty: "A→Type" }  ],
                    variables: [ ],
                    hypotheses: [ { ty: "(∃x∈A,P(x))∨(∃x∈A,Q(x))" } ],
                    conclusion: { ty: "∃x∈A,(P(x)∨Q(x))" },
                },
                {
                    parameters: [ { name: "A", ty: "Type" }, { name: "P", ty: "Type" }, { name: "Q", ty: "A→Type" }  ],
                    variables: [ { name: "a", ty: "A" } ],
                    hypotheses: [ { ty: "P∨(∃x∈A,Q(x))" } ],
                    conclusion: { ty: "∃x∈A,(P∨Q(x))" },
                },
            ]
          },
          { name: "∃∀⇒",
            rules: [ "impI", "impE", "exE", "exI", "allI", "allE" ],
            levels: [
                {
                    parameters: [ { name: "A", ty: "Type" }, { name: "B", ty: "Type" }, { name: "P", ty: "A×B→Type" } ],
                    variables: [ ],
                    hypotheses: [ { ty: "∃x∈A,∀y∈B,P(x,y)" } ],
                    conclusion: { ty: "∀y∈B,∃x∈A,P(x,y)" },
                },
                {
                    parameters: [ { name: "A", ty: "Type" }, { name: "P", ty: "A→Type" }, { name: "Q", ty: "Type" } ],
                    variables: [ ],
                    hypotheses: [ { ty: "(∃x∈A,P(x))⇒Q" } ],
                    conclusion: { ty: "∀x∈A,(P(x)⇒Q)" },
                },
                {
                    parameters: [ { name: "A", ty: "Type" }, { name: "P", ty: "A→Type" }, { name: "Q", ty: "Type" } ],
                    variables: [ ],
                    hypotheses: [ { ty: "∀x∈A,(P(x)⇒Q)" } ],
                    conclusion: { ty: "(∃x∈A,P(x))⇒Q" },
                },
                {
                    parameters: [ { name: "A", ty: "Type" }, { name: "P", ty: "A→Type" }, { name: "Q", ty: "Type" } ],
                    variables: [ ],
                    hypotheses: [ { ty: "∀x∈A,P(x)" } ],
                    conclusion: { ty: "(∃x∈A,(P(x)⇒Q))⇒Q" },
                },
                {
                    parameters: [ { name: "A", ty: "Type" }, { name: "P", ty: "A→Type" }, { name: "Q", ty: "Type" } ],
                    variables: [ ],
                    hypotheses: [ { ty: "∀x∈A,P(x)" }, { ty: "∃x∈A,(P(x)⇒Q)"} ],
                    conclusion: { ty: "Q" },
                },
                {
                    parameters: [ { name: "A", ty: "Type" }, { name: "P", ty: "A→Type" }, { name: "Q", ty: "A→Type" } ],
                    variables: [ ],
                    hypotheses: [ { ty: "∀x∈A,(P(x)⇒Q(x))" }, { ty: "∃x∈A,P(x)"} ],
                    conclusion: { ty: "∃x∈A,Q(x)" },
                },
                {
                    parameters: [ { name: "A", ty: "Type" }, { name: "P", ty: "A→Type" }, { name: "Q", ty: "Type" } ],
                    variables: [ ],
                    hypotheses: [ { ty: "∃x∈A,(P(x)⇒Q)" } ],
                    conclusion: { ty: "(∀x∈A,P(x))⇒Q" },
                },
            ]
          },
          { name: "∃∀∧⇒⊤⊥", // ∨ not yet used
            rules: [ "andI", "andE", "orE", "orI1", "orI2", "exE", "exI", "allI", "allE", "topI", "botE", "impI", "impE" ],
            levels: [
                {
                    parameters: [ { name: "A", ty: "Type" }, { name: "B", ty: "Type" }, { name: "C", ty: "Type" }, { name: "P", ty: "A×B→Type" }, { name: "Q", ty: "B×C→Type" }, { name: "R", ty: "A×C→Type" } ],
                    variables: [ ],
                    hypotheses: [ { ty: "∀x∈A,∃y∈B,P(x,y)" }, { ty: "∀y∈B,∃z∈C,Q(y,z)" }, { ty: "∀x∈A,∀y∈B,∀z∈C,((P(x,y)∧Q(y,z))⇒R(x,z))" }, ],
                    conclusion: { ty: "∀x∈A,∃z∈C,R(x,z)" },
                },
                {
                    parameters: [ { name: "A", ty: "Type" }, { name: "P", ty: "A→Type" }, { name: "Q", ty: "A→Type" } ],
                    variables: [ ],
                    hypotheses: [ { ty: "∀x∈A,P(x)" }, { ty: "∃x∈A,Q(x)"} ],
                    conclusion: { ty: "∃x∈A,(P(x)∧Q(x))" },
                },
                {
                    parameters: [ { name: "A", ty: "Type" }, { name: "P", ty: "A→Type" } ],
                    variables: [ ],
                    hypotheses: [ { ty: "∀x∈A,P(x)" }, { ty: "∃x∈A,⊤"} ],
                    conclusion: { ty: "∃x∈A,P(x)" },
                },
                {
                    parameters: [ { name: "A", ty: "Type" }, { name: "P", ty: "Type" }, { name: "Q", ty: "Type" } ],
                    variables: [ ],
                    hypotheses: [ { ty: "P⇒∀x∈A,⊥" }, { ty: "∃x∈A,⊤"} ],
                    conclusion: { ty: "P⇒Q" },
                },
            ]
          },
      ]
    },
    { name: "Negation world",
      stages: [
          { name: "¬⇒⊥",
            rules: [ "impI", "impE", "negI", "negE", "botE" ],
            levels: [
                {
                    parameters: [ { name: "P", ty: "Type" }, { name: "Q", ty: "Type" } ],
                    variables: [ ],
                    hypotheses: [ { ty: "¬P" }, { ty: "P" } ],
                    conclusion: { ty: "Q" },
                    trivial: true,
                    hint: "negationHint",
                },
                {
                    parameters: [ { name: "P", ty: "Type" } ],
                    variables: [ ],
                    hypotheses: [ { ty: "P⇒⊥" } ],
                    conclusion: { ty: "¬P" },
                    trivial: true,
                },
                {
                    parameters: [ { name: "P", ty: "Type" } ],
                    variables: [ ],
                    hypotheses: [ { ty: "¬P" } ],
                    conclusion: { ty: "P⇒⊥" },
                    trivial: true,
                },
                {
                    parameters: [ { name: "P", ty: "Type" } ],
                    variables: [ ],
                    hypotheses: [ { ty: "P" } ],
                    conclusion: { ty: "¬¬P" },
                },
                {
                    parameters: [ { name: "P", ty: "Type" }, { name: "Q", ty: "Type" } ],
                    variables: [ ],
                    hypotheses: [ { ty: "P⇒Q" } ],
                    conclusion: { ty: "¬Q⇒¬P" },
                },
            ]
          },
          { name: "¬⇒∧∨",
            rules: [ "negI", "negE", "impE", "impI", "andI", "andE", "orI1", "orI2", "orE" ],
            levels: [
                {
                    parameters: [ { name: "P", ty: "Type" }, { name: "Q", ty: "Type" } ],
                    variables: [ ],
                    hypotheses: [ { ty: "Q∨¬P" } ],
                    conclusion: { ty: "P⇒Q" },
                },
                {
                    parameters: [ { name: "P", ty: "Type" }, { name: "Q", ty: "Type" } ],
                    variables: [ ],
                    hypotheses: [ { ty: "¬(P∨Q)" } ],
                    conclusion: { ty: "¬P∧¬Q" },
                },
                {
                    parameters: [ { name: "P", ty: "Type" }, { name: "Q", ty: "Type" } ],
                    variables: [ ],
                    hypotheses: [ { ty: "¬P∧¬Q" } ],
                    conclusion: { ty: "¬(P∨Q)" },
                },
                {
                    parameters: [ { name: "P", ty: "Type" }, { name: "Q", ty: "Type" } ],
                    variables: [ ],
                    hypotheses: [ { ty: "¬P∨¬Q" } ],
                    conclusion: { ty: "¬(P∧Q)" },
                },
                {
                    parameters: [ { name: "P", ty: "Type" }, { name: "Q", ty: "Type" } ],
                    variables: [ ],
                    hypotheses: [ { ty: "P∧¬Q" } ],
                    conclusion: { ty: "¬(P⇒Q)" },
                },
                {
                    parameters: [ { name: "P", ty: "Type" }, { name: "Q", ty: "Type" } ],
                    variables: [ ],
                    hypotheses: [ { ty: "P∨Q" }, { ty: "¬P" } ],
                    conclusion: { ty: "Q" },
                },
            ]
          },
          { name: "¬∀∃⇒∨⊤",                        // ∧, ⊥ not yet used
            rules: [ "negI", "negE", "allI", "allE", "exI", "exE", "orE", "orI1", "orI2", "orE", "topI", "impE", "impI" ],
            levels: [
                {
                    parameters: [ { name: "A", ty: "Type" }, { name: "P", ty: "A→Type" } ],
                    variables: [ ],
                    hypotheses: [ { ty: "¬∃x∈A,P(x)" } ],
                    conclusion: { ty: "∀x∈A,¬P(x)" },
                },
                {
                    parameters: [ { name: "A", ty: "Type" }, { name: "P", ty: "A→Type" } ],
                    variables: [ ],
                    hypotheses: [ { ty: "∀x∈A,¬P(x)" } ],
                    conclusion: { ty: "¬∃x∈A,P(x)" },
                },
                {
                    parameters: [ { name: "A", ty: "Type" }, { name: "P", ty: "A→Type" } ],
                    variables: [ ],
                    hypotheses: [ { ty: "∃x∈A,¬P(x)" } ],
                    conclusion: { ty: "¬∀x∈A,P(x)" },
                },
                {
                    parameters: [ { name: "A", ty: "Type" }, { name: "P", ty: "A→Type" }, { name: "Q", ty: "Type" } ],
                    variables: [ ],
                    hypotheses: [ { ty: "(∃x∈A,¬P(x))∨Q" } ],
                    conclusion: { ty: "(∀x∈A,P(x))⇒Q" },
                },
                {
                    parameters: [ { name: "A", ty: "Type" }, { name: "P", ty: "A→Type" }, { name: "Q", ty: "Type" } ],
                    variables: [ ],
                    hypotheses: [ { ty: "(∃x∈A,¬P(x))∨Q" }, { ty: "∃x∈A,⊤" } ],
                    conclusion: { ty: "∃x∈A,(P(x)⇒Q)" },
                },
            ]
          },
          { name: "¬¬₁",
            rules: [ "impI", "impE", "cnegI", "negE", "andI", "andE", "orI1", "orI2", "orE", "allI", "allE", "exI", "exE" ],
            levels: [
                {
                    parameters: [ { name: "P", ty: "Type" } ],
                    variables: [ ],
                    hypotheses: [ { ty : "¬¬P" } ],
                    conclusion: { ty: "P" },
                    hint: "contradictionHint",
                },
                {
                    parameters: [ { name: "P", ty: "Type" }, { name: "Q", ty: "Type" } ],
                    variables: [ ],
                    hypotheses: [ { ty: "¬Q⇒¬P" } ],
                    conclusion: { ty: "P⇒Q" },
                },
                {
                    parameters: [ { name: "P", ty: "Type" }, { name: "Q", ty: "Type" } ],
                    variables: [ ],
                    hypotheses: [ { ty: "¬(P⇒Q)" } ],
                    conclusion: { ty: "P∧¬Q" },
                },
                {
                    parameters: [ { name: "P", ty: "Type" }, { name: "Q", ty: "Type" } ],
                    variables: [ ],
                    hypotheses: [ { ty: "¬(P∧Q)" } ],
                    conclusion: { ty: "¬P∨¬Q" },
                },
                {
                    parameters: [ { name: "A", ty: "Type" }, { name: "P", ty: "A→Type" } ],
                    variables: [ ],
                    hypotheses: [ { ty: "¬∀x∈A,P(x)" } ],
                    conclusion: { ty: "∃x∈A,¬P(x)" },
                },
                {
                    parameters: [ { name: "P", ty: "Type" }, { name: "Q", ty: "Type" } ],
                    variables: [ ],
                    hypotheses: [ { ty: "P⇒Q" } ],
                    conclusion: { ty: "Q∨¬P" },
                },
                {
                    parameters: [ { name: "P", ty: "Type" } ],
                    variables: [ ],
                    hypotheses: [ ],
                    conclusion: { ty: "P∨¬P" },
                },
            ]
          },
          { name: "¬¬₂",
            rules: [ "impI", "impE", "cnegI", "negE", "andE", "andI", "orI1", "orI2", "orE", "allI", "allE", "exI", "exE" ],
            levels: [
                {
                    parameters: [ { name: "P", ty: "Type" }, { name: "Q", ty: "Type" } ],
                    variables: [ ],
                    hypotheses: [ ],
                    conclusion: { ty: "((P⇒Q)⇒P)⇒P" },
                },
                {
                    parameters: [ { name: "P", ty: "Type" }, { name: "Q", ty: "Type" } ],
                    variables: [ ],
                    hypotheses: [ ],
                    conclusion: { ty: "(P⇒Q)∨(Q⇒P)" },
                },
                {
                    parameters: [ { name: "P", ty: "Type" }, { name: "Q", ty: "Type" }, { name: "R", ty: "Type" }, { name: "S", ty: "Type" } ],
                    variables: [ ],
                    hypotheses: [ { ty: "P⇒Q" }, { ty: "R⇒S" } ],
                    conclusion: { ty: "(P⇒S)∨(R⇒Q)" },
                },
                {
                    parameters: [ { name: "P", ty: "Type" }, { name: "Q", ty: "Type" }, { name: "R", ty: "Type" } ],
                    variables: [ ],
                    hypotheses: [ { ty: "(P∧Q)⇒R" } ],
                    conclusion: { ty: "(P⇒R)∨(Q⇒R)" },
                },
                {
                    parameters: [ { name: "P", ty: "Type" } ],
                    variables: [ ],
                    hypotheses: [ ],
                    conclusion: { ty: "(¬P⇒P)⇒P" },
                },
                {
                    parameters: [ { name: "P", ty: "Type" }, { name: "Q", ty: "Type" }, { name: "R", ty: "Type" } ],
                    variables: [ ],
                    hypotheses: [ ],
                    conclusion: { ty: "(P⇒Q)∨(Q⇒R)" },
                },
                {
                    parameters: [ { name: "A", ty: "Type" }, { name: "P", ty: "A→Type" } ],
                    variables: [ ],
                    hypotheses: [ { ty : "∃x∈A,⊤" } ],
                    conclusion: { ty: "∃x∈A,(P(x)⇒∀y∈A,P(y))" },
                },
            ]
          },
      ]
    },
    { name: "Algebra world",
      stages: [
          { name: "=",
            rules: [ "alg" ],
            levels: [
                {
                    parameters: [ { name: "x", ty: "ℤ" } ],
                    variables: [ ],
                    hypotheses: [ ],
                    conclusion: { ty: "x=x" },
                    trivial: true,
                    hint: "algebraHint",
                },
                {
                    parameters: [ { name: "x", ty: "ℤ" } ],
                    variables: [ ],
                    hypotheses: [ ],
                    conclusion: { ty: "(x+1)²=x²+2*x+1" },
                    trivial: true,
                    hint: "multiplicationHint",
                },
                {
                    parameters: [ { name: "x", ty: "ℤ" }, { name: "y", ty: "ℤ" } ],
                    variables: [ ],
                    hypotheses: [ { ty: "x=y"} ],
                    conclusion: { ty: "y=x" },
                    trivial: true,
                    hint: "algebra2Hint",
                },
                {
                    parameters: [ { name: "x", ty: "ℤ" }, { name: "y", ty: "ℤ" }, { name: "z", ty: "ℤ" } ],
                    variables: [ ],
                    hypotheses: [ { ty: "x=y"}, { ty: "y=z"} ],
                    conclusion: { ty: "x=z" },
                    trivial: true,
                    hint: "algebra3Hint",
                },
                {
                    parameters: [ { name: "a", ty: "ℤ" }, { name: "b", ty: "ℤ" }, { name: "c", ty: "ℤ" }, { name: "d", ty: "ℤ" } ],
                    variables: [ ],
                    hypotheses: [ { ty: "a=b²+2*d" }, { ty: "c=d²−2*b" } ],
                    conclusion: { ty: "a*b+c*d=b³+d³" },
                    trivial: true,
                    hint: "algebra4Hint",
                },
            ],
          },
          { name: "=≠∧",
            rules: [ "andE", "andI", "negE", "cnegI", "alg" ],
            levels: [
                {
                    parameters: [ { name: "x", ty: "ℤ" }, { name: "y", ty: "ℤ" } ],
                    variables: [ ],
                    hypotheses: [ { ty: "y≠5"}, { ty: "x²+y=14"} ],
                    conclusion: { ty: "x≠3" },
                    hint: "neqHint",
                },
                {
                    parameters: [ { name: "x", ty: "ℤ" } ],
                    variables: [ ],
                    hypotheses: [ { ty: "x²≠1"} ],
                    conclusion: { ty: "(x≠1)∧(x≠−1)" },
                    saveable: {
                        parameters: [ { name: "x", ty: "ℤ" } ],
                        variables: [ ],
                        hypotheses: [ { ty: "x²≠1"} ],
                        conclusion: { ty: "(x≠1)∧(x≠∸1)" },
                    }
                },
                {
                    parameters: [ { name: "x", ty: "ℤ" }, { name: "y", ty: "ℤ" } ],
                    variables: [ ],
                    hypotheses: [ { ty: "y+x=2*y−x"}, { ty: "¬((x=0)∧(y=0))" } ],
                    conclusion: { ty: "y≠0" },
                },
            ],
          },
          { name: "∨=",
            rules: [ "orI1", "orI2", "orE", "expr", "alg", "integral" ],
            levels: [
                {
                    parameters: [ ],
                    variables: [ { name: "x", ty: "ℤ" }, { name: "y", ty: "ℤ" } ],
                    hypotheses: [ { ty: "(x=y+1)∨(2*x=3−y)" } ],
                    conclusion: { ty: "2*x²−x*y−y²=5*x−2*y−3" },
                    trivial: true,
                    hint: "setsHint",
                },
                {
                    parameters: [ ],
                    variables: [ { name: "x", ty: "ℤ" }, { name: "y", ty: "ℤ" } ],
                    hypotheses: [ { ty: "(x+y=1)∨(x−y=1)" } ],
                    conclusion: { ty: "x²+1=y²+2*x" },
                    trivial: true,
                },
                {
                    parameters: [ ],
                    variables: [ { name: "x", ty: "ℤ" }, { name: "y", ty: "ℤ" } ],
                    hypotheses: [ { ty: "x*y=0" } ],
                    conclusion: { ty: "(x=0)∨(y=0)" },
                    trivial: true,
                    hint: "integralHint",
                },
                {
                    parameters: [ ],
                    variables: [ { name: "x", ty: "ℤ" } ],
                    hypotheses: [ { ty: "x²=0" } ],
                    conclusion: { ty: "x=0" },
                },
                {
                    parameters: [ ],
                    variables: [ { name: "x", ty: "ℤ" } ],
                    hypotheses: [ { ty: "x²=x" } ],
                    conclusion: { ty: "(x=0)∨(x=1)" },
                    hint: "exprHint",
                },
                {
                    parameters: [ ],
                    variables: [ { name: "x", ty: "ℤ" } ],
                    hypotheses: [ { ty: "(x²−x−2=0)∨(x²−1=0)" } ],
                    conclusion: { ty: "(x=2)∨((x=1)∨(x=−1))" },
                    saveable: {
                        parameters: [ ],
                        variables: [ { name: "x", ty: "ℤ" } ],
                        hypotheses: [ { ty: "(x²−x−2=0)∨(x²−1=0)" } ],
                        conclusion: { ty: "(x=2)∨((x=1)∨(x=∸1))" },
                    }
                },
                {
                    parameters: [ ],
                    variables: [ { name: "x", ty: "ℤ" } ],
                    hypotheses: [ { ty: "(x²−2*x−3=0)∨(x²+3*x+2=0)" } ],
                    conclusion: { ty: "(x=3)∨((x=−1)∨(x=−2))" },
                    saveable: {
                        parameters: [ ],
                        variables: [ { name: "x", ty: "ℤ" } ],
                        hypotheses: [ { ty: "(x²−2*x−3=0)∨(x²+3*x+2=0)" } ],
                        conclusion: { ty: "(x=3)∨((x=∸1)∨(x=∸2))" },
                    }
                },
            ],
          },
          { name: "∣∃=",
            rules: [ "exE", "exI", "expr", "alg" ],
            levels: [
                {
                    parameters: [ ],
                    variables: [ { name: "n", ty: "ℤ" } ],
                    hypotheses: [ { ty: "∃k∈ℤ,(n=2*k)" } ],
                    conclusion: { ty: "∃k∈ℤ,(n²=2*k)" },
                },
                // 0 is not synthesizing )-:
                // {
                //     parameters: [ ],
                //     variables: [ { name: "a", ty: "ℤ" } ],
                //     hypotheses: [ ],
                //     conclusion: { ty: "∃k∈ℤ,(0=k*a)" },
                // },
                {
                    parameters: [ ],
                    variables: [ { name: "b", ty: "ℤ" } ],
                    hypotheses: [ ],
                    conclusion: { ty: "∃k∈ℤ,(b=k*1)" },
                },
                {
                    parameters: [ ],
                    variables: [ { name: "a", ty: "ℤ" }, { name: "b", ty: "ℤ" } ],
                    hypotheses: [ { ty: "∃k∈ℤ,(b=k*a)" } ],
                    conclusion: { ty: "∃k∈ℤ,(2*b=k*a)" },
                    // hypotheses: [ { ty: "a ∣ b" } ],
                    // conclusion: { ty: "a ∣ 2*b" },
                },
                {
                    parameters: [ ],
                    variables: [ { name: "a", ty: "ℤ" }, { name: "b", ty: "ℤ" } ],
                    hypotheses: [ { ty: "∃k∈ℤ,(b=k*a)" } ],
                    conclusion: { ty: "∃k∈ℤ,(b+a=k*a)" },
                },
                {
                    parameters: [ ],
                    variables: [ { name: "a", ty: "ℤ" }, { name: "b", ty: "ℤ" } ],
                    hypotheses: [ { ty: "∃k∈ℤ,(b=k*a)" } ],
                    conclusion: { ty: "∃k∈ℤ,(b²=k*a²)" },
                },
                {
                    parameters: [ ],
                    variables: [ { name: "a", ty: "ℤ" }, { name: "b", ty: "ℤ" }, { name: "c", ty: "ℤ" } ],
                    hypotheses: [ { ty: "∃k∈ℤ,(b=k*a)" } ],
                    conclusion: { ty: "∃k∈ℤ,(b*c=k*a*c)" },
                },
                {
                    parameters: [ ],
                    variables: [ { name: "a", ty: "ℤ" }, { name: "b", ty: "ℤ" }, { name: "c", ty: "ℤ" } ],
                    hypotheses: [ { ty: "∃k∈ℤ,(b=k*a)" } ],
                    conclusion: { ty: "∃k∈ℤ,(b*c=k*a)" },
                },
                {
                    parameters: [ ],
                    variables: [ { name: "a", ty: "ℤ" }, { name: "b", ty: "ℤ" }, { name: "c", ty: "ℤ" } ],
                    hypotheses: [ { ty: "∃k∈ℤ,(b=k*a)" }, { ty: "∃k∈ℤ,(c=k*a)" } ],
                    conclusion: { ty: "∃k∈ℤ,(b+c=k*a)" },
                },
                {
                    parameters: [ ],
                    variables: [ { name: "a", ty: "ℤ" }, { name: "b", ty: "ℤ" }, { name: "c", ty: "ℤ" } ],
                    hypotheses: [ { ty: "∃k∈ℤ,(b=k*a)" }, { ty: "∃k∈ℤ,(c=k*b)" } ],
                    conclusion: { ty: "∃k∈ℤ,(c=k*a)" },
                },
            ],
          },
          { name: "≡∃=",
            rules: [ "exE", "exI", "expr", "alg" ],
            levels: [
                {
                    parameters: [ ],
                    variables: [ { name: "a", ty: "ℤ" }, { name: "n", ty: "ℤ" } ],
                    hypotheses: [ ],
                    conclusion: { ty: "∃k∈ℤ,(a−a=k*n)" },
                },
                {
                    parameters: [ ],
                    variables: [ { name: "a", ty: "ℤ" }, { name: "b", ty: "ℤ" }, { name: "n", ty: "ℤ" } ],
                    hypotheses: [ { ty: "∃k∈ℤ,(a−b=k*n)" } ],
                    conclusion: { ty: "∃k∈ℤ,(b−a=k*n)" },
                },
                {
                    parameters: [ ],
                    variables: [ { name: "a", ty: "ℤ" }, { name: "b", ty: "ℤ" }, { name: "n", ty: "ℤ" } ],
                    hypotheses: [ { ty: "∃k∈ℤ,(a−b=k*n)" } ],
                    conclusion: { ty: "∃k∈ℤ,(a−b=k*(−n))" },
                    saveable: {
                        parameters: [ ],
                        variables: [ { name: "a", ty: "ℤ" }, { name: "b", ty: "ℤ" }, { name: "n", ty: "ℤ" } ],
                        hypotheses: [ { ty: "∃k∈ℤ,(a−b=k*n)" } ],
                        conclusion: { ty: "∃k∈ℤ,(a−b=k*(∸n))" },
                    }
                },
                {
                    parameters: [ ],
                    variables: [ { name: "a", ty: "ℤ" }, { name: "b", ty: "ℤ" }, { name: "c", ty: "ℤ" }, { name: "n", ty: "ℤ" } ],
                    hypotheses: [ { ty: "∃k∈ℤ,(a−b=k*n)" }, { ty: "∃k∈ℤ,(b−c=k*n)" } ],
                    conclusion: { ty: "∃k∈ℤ,(a−c=k*n)" },
                },
                {
                    parameters: [ ],
                    variables: [ { name: "a", ty: "ℤ" }, { name: "b", ty: "ℤ" }, { name: "c", ty: "ℤ" }, { name: "n", ty: "ℤ" } ],
                    hypotheses: [ { ty: "∃k∈ℤ,(a−b=k*n)" } ],
                    conclusion: { ty: "∃k∈ℤ,(a*c−b*c=k*n)" },
                },
                {
                    parameters: [ ],
                    variables: [ { name: "a", ty: "ℤ" }, { name: "b", ty: "ℤ" } ],
                    hypotheses: [ ],
                    conclusion: { ty: "∃k∈ℤ,(a−b=k*1)" },
                },
                {
                    parameters: [ ],
                    variables: [ { name: "a", ty: "ℤ" }, { name: "b", ty: "ℤ" } ],
                    hypotheses: [ { ty: "∃k∈ℤ,(a−b=k*0)" } ],
                    conclusion: { ty: "a=b" },
                },
                {
                    parameters: [ ],
                    variables: [ { name: "a", ty: "ℤ" }, { name: "b", ty: "ℤ" }, { name: "n", ty: "ℤ" } ],
                    hypotheses: [ { ty: "∃k∈ℤ,(a−b=k*n)" } ],
                    conclusion: { ty: "∃k∈ℤ,(a²−b²=k*n)" },
                },
                {
                    parameters: [ ],
                    variables: [ { name: "a", ty: "ℤ" }, { name: "b", ty: "ℤ" }, { name: "c", ty: "ℤ" }, { name: "d", ty: "ℤ" }, { name: "n", ty: "ℤ" } ],
                    hypotheses: [ { ty: "∃k∈ℤ,(a−c=k*n)" }, { ty: "∃k∈ℤ,(b−d=k*n)" } ],
                    conclusion: { ty: "∃k∈ℤ,((a+b)−(c+d)=k*n)" },
                },
                {
                    parameters: [ ],
                    variables: [ { name: "a", ty: "ℤ" }, { name: "b", ty: "ℤ" }, { name: "c", ty: "ℤ" }, { name: "d", ty: "ℤ" }, { name: "n", ty: "ℤ" } ],
                    hypotheses: [ { ty: "∃k∈ℤ,((a+b)−(c+d)=k*n)" }, { ty: "∃k∈ℤ,(b−d=k*n)" } ],
                    conclusion: { ty: "∃k∈ℤ,(a−c=k*n)" },
                },
            ],
          },
          { name: "≡∣∃=",
            rules: [ "exE", "exI", "expr", "alg" ],
            levels: [
                {
                    parameters: [ ],
                    variables: [ { name: "a", ty: "ℤ" }, { name: "b", ty: "ℤ" }, { name: "m", ty: "ℤ" }, { name: "n", ty: "ℤ" } ],
                    hypotheses: [ { ty: "∃k∈ℤ,(a−b=k*n)" }, { ty: "∃k∈ℤ,(n=k*m)" } ],
                    conclusion: { ty: "∃k∈ℤ,(a−b=k*m)" },
                },
                {
                    parameters: [ ],
                    variables: [ { name: "a", ty: "ℤ" }, { name: "b", ty: "ℤ" }, { name: "c", ty: "ℤ" }, { name: "m", ty: "ℤ" }, { name: "n", ty: "ℤ" } ],
                    hypotheses: [ { ty: "∃k∈ℤ,(a−b=k*n)" }, { ty: "∃k∈ℤ,(c=k*m)" } ],
                    conclusion: { ty: "∃k∈ℤ,(a*c−b*c=k*(m*n))" },
                },
                // Just for testing number systems and subtypes
                // {
                //     parameters: [ ],
                //     variables: [ { name: "x", ty: "ℝ" }, { name: "y", ty: "𝕊" } ],
                //     hypotheses: [ ],
                //     conclusion: { ty: "∃a∈ℝ,∃b∈𝕊,((a+a=a)∧(b+b=b))" },
                // },
            ],
          },
          { name: "∀=≠",
            rules: [ "allE", "allI", "cnegI", "negE", "expr", "alg" ],
            levels: [
                {
                    parameters: [ ],
                    variables: [ { name: "a", ty: "ℤ" } ],
                    hypotheses: [ { ty: "∀x∈ℤ,(a*x=0)" } ],
                    conclusion: { ty: "a=0" },
                },
                {
                    parameters: [ ],
                    variables: [ { name: "a", ty: "ℤ" } ],
                    hypotheses: [ { ty: "∀x∈ℤ,(a*x²+6*x=a)" } ],
                    conclusion: { ty: "a=−4" },
                    saveable: {
                        parameters: [ ],
                        variables: [ { name: "a", ty: "ℤ" } ],
                        hypotheses: [ { ty: "∀x∈ℤ,(a*x²+6*x=a)" } ],
                        conclusion: { ty: "a=∸4" },
                    }
                },
                {
                    parameters: [ ],
                    variables: [ { name: "a", ty: "ℤ" } ],
                    hypotheses: [ { ty: "∀x∈ℤ,(a*x≠0)" } ],
                    conclusion: { ty: "a≠0" },
                },
                {
                    parameters: [ ],
                    variables: [ { name: "a", ty: "ℤ" } ],
                    hypotheses: [ { ty: "∀k∈ℤ,(a≠3*k)" } ],
                    conclusion: { ty: "∀k∈ℤ,(a≠6*k)" },
                },
                {
                    parameters: [ ],
                    variables: [ ],
                    hypotheses: [ { ty: "∀x∈ℤ,(x²≠18)" } ],
                    conclusion: { ty: "∀x∈ℤ,(x²≠2)" },
                },
                {
                    parameters: [ ],
                    variables: [ ],
                    hypotheses: [ { ty: "∀x∈ℤ,(x²≠−4)" } ],
                    conclusion: { ty: "∀x∈ℤ,(x²≠−1)" },
                    saveable: {
                        parameters: [ ],
                        variables: [ ],
                        hypotheses: [ { ty: "∀x∈ℤ,(x²≠∸4)" } ],
                        conclusion: { ty: "∀x∈ℤ,(x²≠∸1)" },
                    }
                },
                {
                    parameters: [ { name: "a", ty: "ℤ" }, { name: "b", ty: "ℤ" } ],
                    variables: [ ],
                    hypotheses: [ { ty: "∀k∈ℤ,(a*k≠3*b−a)" } ],
                    conclusion: { ty: "∀k∈ℤ,(a*k≠b)" },
                },
                {
                    parameters: [ { name: "a", ty: "ℤ" }, { name: "b", ty: "ℤ" }, { name: "c", ty: "ℤ" } ],
                    variables: [ ],
                    hypotheses: [ { ty: "∀k∈ℤ,(a*k*c≠b*c)" } ],
                    conclusion: { ty: "∀k∈ℤ,(a*k≠b)" },
                },
            ],
          },
          { name: "∃∀=",
            rules: [ "allE", "allI", "exI", "exE", "expr", "alg" ],
            levels: [
                {
                    parameters: [ ],
                    variables: [ ],
                    hypotheses: [ ],
                    conclusion: { ty: "∀x∈ℝ,∃y∈ℝ,(x+y=0)" },
                },
                {
                    parameters: [ ],
                    variables: [ ],
                    hypotheses: [ ],
                    conclusion: { ty: "∀x∈ℝ,∃y∈ℝ,(x+y=x)" },
                },
                {
                    parameters: [ ],
                    variables: [ ],
                    hypotheses: [ ],
                    conclusion: { ty: "∃y∈ℝ,∀x∈ℝ,(x+y=x)" },
                },
                {
                    parameters: [ ],
                    variables: [ ],
                    hypotheses: [ ],
                    conclusion: { ty: "∃y∈ℝ,∀x∈ℝ,(x*y=x)" },
                },
                {
                    parameters: [ ],
                    variables: [ ],
                    hypotheses: [ ],
                    conclusion: { ty: "∃y∈ℝ,∀x∈ℝ,(x*y=y)" },
                },
                // TODO: How can we give them 1≠0?  Probably rlqe can prove it... if we allow it to prove ≠s.
                // {
                //     parameters: [ ],
                //     variables: [ ],
                //     hypotheses: [ ],
                //     conclusion: { ty: "¬∃y∈ℝ,∀x∈ℝ,(x+y=0)" },
                // },
                // {
                //     parameters: [ ],
                //     variables: [ ],
                //     hypotheses: [ ],
                //     conclusion: { ty: "¬∀x∈ℝ,∃y∈ℝ,(x*y=1)" },
                // },
            ],
          },
      ],
    },
    { name: "Inequality world",
      // server: true,
      stages: [
          { name: "<",
            rules: [ "alg" ],
            levels: [
                {
                    parameters: [ { name: "x", ty: "ℝ" }, { name: "y", ty: "ℝ" } ],
                    variables: [ ],
                    hypotheses: [ { ty: "x<y+1" } ],
                    conclusion: { ty: "x−1<y" },
                },
                // {
                //     parameters: [ { name: "x", ty: "ℝ" }, { name: "y", ty: "ℝ" } ],
                //     variables: [ ],
                //     hypotheses: [ { ty : "(0:ℝ)<x" }, { ty: "x<y" } ],
                //     conclusion: { ty: "x²<y²" },
                // },
            ],
          },
          { name: "∀⇒<",
            rules: [ "allI", "allE", "impE", "impI", "expr", "alg" ],
            levels: [
                {               // x pos inf => x+1 pos inf
                    parameters: [ ],
                    variables: [ { name: "x", ty: "𝕊" } ],
                    hypotheses: [ { ty: "∀u∈ℝ,(u<x)" } ],
                    conclusion: { ty: "∀u∈ℝ,(u<x+1)" },
                },
                {               // x pos inf => x-1 pos inf
                    parameters: [ ],
                    variables: [ { name: "x", ty: "𝕊" } ],
                    hypotheses: [ { ty: "∀u∈ℝ,(u<x)" } ],
                    conclusion: { ty: "∀u∈ℝ,(u<x−1)" },
                },
                {               // x pos inf => x+q pos inf
                    parameters: [ ],
                    variables: [ { name: "x", ty: "𝕊" }, { name: "q", ty: "ℝ" }, ],
                    hypotheses: [ { ty: "∀u∈ℝ,(u<x)" } ],
                    conclusion: { ty: "∀u∈ℝ,(u<x+q)" },
                },
                // {
                //     parameters: [ { name: "x", ty: "𝕊" } ],
                //     variables: [ ],
                //     hypotheses: [ { ty: "∀u∈ℝ,(u<x)" } ],
                //     conclusion: { ty: "∀u∈ℝ,(u<2*x)" },
                // },
                {               // x,y pos inf => x+y pos inf
                    parameters: [ ],
                    variables: [ { name: "x", ty: "𝕊" }, { name: "y", ty: "𝕊" } ],
                    hypotheses: [ { ty: "∀u∈ℝ,(u<x)" }, { ty: "∀u∈ℝ,(u<y)" } ],
                    conclusion: { ty: "∀u∈ℝ,(u<x+y)" },
                },
                {               // x,y pos inf => x*y pos inf
                    parameters: [ ],
                    variables: [ { name: "x", ty: "𝕊" }, { name: "y", ty: "𝕊" } ],
                    hypotheses: [ { ty: "∀u∈ℝ,(u<x)" }, { ty: "∀u∈ℝ,(u<y)" } ],
                    conclusion: { ty: "∀u∈ℝ,((0<u)⇒(u<x*y))" },
                },
                {               // x neg inf => x+q neg inf
                    parameters: [ ],
                    variables: [ { name: "x", ty: "𝕊" }, { name: "q", ty: "ℝ" }, ],
                    hypotheses: [ { ty: "∀u∈ℝ,(x<u)" } ],
                    conclusion: { ty: "∀u∈ℝ,(x+q<u)" },
                },
                {               // x,y neg inf => x+y neg inf
                    parameters: [ ],
                    variables: [ { name: "x", ty: "𝕊" }, { name: "y", ty: "𝕊" }, ],
                    hypotheses: [ { ty: "∀u∈ℝ,(x<u)" }, { ty: "∀u∈ℝ,(y<u)" } ],
                    conclusion: { ty: "∀u∈ℝ,(x+y<u)" },
                },
                {               // x,y neg inf => x*y pos inf
                    parameters: [ ],
                    variables: [ { name: "x", ty: "𝕊" }, { name: "y", ty: "𝕊" } ],
                    hypotheses: [ { ty: "∀u∈ℝ,(x<u)" }, { ty: "∀u∈ℝ,(y<u)" } ],
                    conclusion: { ty: "∀u∈ℝ,((0<u)⇒(u<x*y))" },
                },
                {               // x pos inf, y neg inf => x*y neg inf
                    parameters: [ ],
                    variables: [ { name: "x", ty: "𝕊" }, { name: "y", ty: "𝕊" } ],
                    hypotheses: [ { ty: "∀u∈ℝ,(u<x)" }, { ty: "∀u∈ℝ,(y<u)" } ],
                    conclusion: { ty: "∀u∈ℝ,((u<0)⇒(x*y<u))" },
                },
            ],
          },
          { name: "∀⇒∧<",
            rules: [ "allI", "allE", "impE", "impI", "andI", "andE", "expr", "alg" ],
            levels: [
                {               // x,y infinitesimal => x+y infinitesimal
                    parameters: [ ],
                    variables: [ { name: "x", ty: "𝕊" }, { name: "y", ty: "𝕊" } ],
                    hypotheses: [ { ty: "∀u∈ℝ,((u>0)⇒((−u<x)∧(x<u)))" }, { ty: "∀u∈ℝ,((u>0)⇒((−u<y)∧(y<u)))" } ],
                    conclusion: { ty: "∀u∈ℝ,((u>0)⇒((−u<x+y)∧(x+y<u)))" },
                    saveable: {
                        parameters: [ ],
                        variables: [ { name: "x", ty: "𝕊" }, { name: "y", ty: "𝕊" } ],
                        hypotheses: [ { ty: "∀u∈ℝ,((u>0)⇒((∸u<x)∧(x<u)))" }, { ty: "∀u∈ℝ,((u>0)⇒((∸u<y)∧(y<u)))" } ],
                        conclusion: { ty: "∀u∈ℝ,((u>0)⇒((∸u<x+y)∧(x+y<u)))" },
                    },

                },
                {               // x,y infinitesimal => x-y infinitesimal
                    parameters: [ ],
                    variables: [ { name: "x", ty: "𝕊" }, { name: "y", ty: "𝕊" } ],
                    hypotheses: [ { ty: "∀u∈ℝ,((u>0)⇒((−u<x)∧(x<u)))" }, { ty: "∀u∈ℝ,((u>0)⇒((−u<y)∧(y<u)))" } ],
                    conclusion: { ty: "∀u∈ℝ,((u>0)⇒((−u<x−y)∧(x−y<u)))" },
                    saveable: {
                        parameters: [ ],
                        variables: [ { name: "x", ty: "𝕊" }, { name: "y", ty: "𝕊" } ],
                        hypotheses: [ { ty: "∀u∈ℝ,((u>0)⇒((∸u<x)∧(x<u)))" }, { ty: "∀u∈ℝ,((u>0)⇒((∸u<y)∧(y<u)))" } ],
                        conclusion: { ty: "∀u∈ℝ,((u>0)⇒((∸u<x−y)∧(x−y<u)))" },
                    }
                },
                {               // x pos infinitesimal => 2x infinitesimal
                    parameters: [ ],
                    variables: [ { name: "x", ty: "𝕊" } ],
                    hypotheses: [ { ty: "x>0"}, { ty: "∀u∈ℝ,((u>0)⇒(x<u))" }, ],
                    conclusion: { ty: "∀u∈ℝ,((u>0)⇒(2*x<u))" },
                },
                {               // x,y pos infinitesimal => x*y infinitesimal
                    parameters: [ ],
                    variables: [ { name: "x", ty: "𝕊" }, { name: "y", ty: "𝕊" } ],
                    hypotheses: [ { ty: "x>0" }, { ty: "y>0" }, { ty: "∀u∈ℝ,((u>0)⇒((−u<x)∧(x<u)))" }, { ty: "∀u∈ℝ,((u>0)⇒((−u<y)∧(y<u)))" } ],
                    conclusion: { ty: "∀u∈ℝ,((u>0)⇒((−u<x*y)∧(x*y<u)))" },
                },
            ],
          },
          { name: "∃∀∧⇒<",
            rules: [ "allE", "allI", "exI", "exE", "andI", "andE", "impI", "impE", "expr", "alg" ],
            levels: [
                {
                    parameters: [ ],
                    variables: [ ],
                    hypotheses: [ ],
                    conclusion: { ty: "∀x∈ℝ,∃y∈ℝ,(x<y)" },
                },
                {
                    parameters: [ ],
                    variables: [ ],
                    hypotheses: [ ],
                    conclusion: { ty: "∀x∈ℝ,∃y∈ℝ,(y<x)" },
                },
                {
                    parameters: [ ],
                    variables: [ ],
                    hypotheses: [ ],
                    conclusion: { ty: "∀x∈ℝ,((0<x)⇒∃y∈ℝ,((0<y)∧(y<x)))" },
                },
                {
                    parameters: [ ],
                    variables: [ { name: "x", ty: "ℝ" }, { name: "y", ty: "ℝ" } ],
                    hypotheses: [ { ty: "x<y" } ],
                    conclusion: { ty: "∃z∈ℝ,((x<z)∧(z<y))" },
                },
                {
                    parameters: [ ],
                    variables: [ { name: "x", ty: "ℝ" }, { name: "y", ty: "ℝ" } ],
                    hypotheses: [ { ty: "x<y" } ],
                    conclusion: { ty: "∃z∈ℝ,∃w∈ℝ,(((x<z)∧(z<w))∧(w<y))" },
                },
            ],
          },
      ],
    },
]

// Take an object that may have extra fields and strip out everything but the intrinsic properties of a level, so that we can JSON.stringify it and use it as a key into localStorage or CouchDB.
export function saveable(level) {
    // For legacy support, so students who completed levels with ∸ will still see them as completed even though we changed the notation to −.
    if(level.saveable) {
        return {
            parameters: level.saveable.parameters,
            variables: level.saveable.variables,
            hypotheses: level.saveable.hypotheses,
            conclusion: level.saveable.conclusion,
        };
    } else {
        return {
            parameters: level.parameters,
            variables: level.variables,
            hypotheses: level.hypotheses,
            conclusion: level.conclusion,
        };
    }
}
